baseURL = "https://bisnis7.com/"
languageCode = "en-us"
title = "Info Bisnis Dan Peluang Usaha 7 Hari Seminggu"
description = "Mengulas topik bisnis mulai dari bisnis online, peluang usaha, usaha mikro kecil menengah, bisnis modal kecil, franchise, mlm hingga investasi."
disableKinds = "RSS"
paginate = 10

[related]
threshold = 80.0
includeNewer = false
toLower = false

  [[related.indices]]
  name = "tag"
  weight = 100.0

  [[related.indices]]
  name = "date"
  weight = 10.0

[taxonomies]
  category = "category"
  tag = "tag"